name: redux
maintainer: John Ryan (@johnpryan)
description: Redux is a predictable state container for Dart and Flutter apps
homepage: https://github.com/fluttercommunity/redux.dart
version: 5.0.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.16.3
  pedantic: ^1.10.0
